apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  # ...
  template:
    # ...
    spec:
      containers:
        # ...
      volumes:
        - name: mi-secreto
          secret:
            secretName: mi-secreto
